# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES += $(shell pwd)/../hdl/spi_master_cs.v
VERILOG_SOURCES += $(shell pwd)/../hdl/spi_master.v
TOPLEVEL = spi_master_cs
MODULE = spi_master_tb

include $(shell cocotb-config --makefiles)/Makefile.sim